// Fichier généré par scripts/build-index.mjs — ne pas modifier à la main.
window.PROJECTS = [
 {
  "model": "claude-46-opus",
  "modelName": "Claude Opus 4.6",
  "family": "claude",
  "type": "learning",
  "title": "SysDesign Academy — Architecture Web Fullstack",
  "slug": "architecture",
  "url": "claude-46-opus/architecture.html",
  "source": "claude-46-opus/architecture.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-46-opus",
  "modelName": "Claude Opus 4.6",
  "family": "claude",
  "type": "learning",
  "title": "Symfony Architect · Prépa entretien Backend",
  "slug": "architecture-symfony",
  "url": "claude-46-opus/architecture-symfony.html",
  "source": "claude-46-opus/architecture-symfony.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-46-opus",
  "modelName": "Claude Opus 4.6",
  "family": "claude",
  "type": "learning",
  "title": "Dev Principles Academy — SOLID, DRY, KISS, YAGNI",
  "slug": "solid",
  "url": "claude-46-opus/solid.html",
  "source": "claude-46-opus/solid.html",
  "playable": true,
  "react": false,
  "date": "2026-03-25"
 },
 {
  "model": "claude-47-opus",
  "modelName": "Claude Opus 4.7",
  "family": "claude",
  "type": "tool",
  "title": "2D Skeleton Animator",
  "slug": "2d-animator",
  "url": "claude-47-opus/2d-animator.html",
  "source": "claude-47-opus/2d-animator.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-47-opus",
  "modelName": "Claude Opus 4.7",
  "family": "claude",
  "type": "learning",
  "title": "Express Mastery — Prep entretien fullstack",
  "slug": "javascript_express",
  "url": "claude-47-opus/javascript_express.html",
  "source": "claude-47-opus/javascript_express.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-47-opus",
  "modelName": "Claude Opus 4.7",
  "family": "claude",
  "type": "learning",
  "title": "Jest Mastery · Préparation entretien",
  "slug": "javascript_jest",
  "url": "claude-47-opus/javascript_jest.html",
  "source": "claude-47-opus/javascript_jest.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-47-opus",
  "modelName": "Claude Opus 4.7",
  "family": "claude",
  "type": "learning",
  "title": "NestJS Mastery — Prep entretien fullstack",
  "slug": "javascript_nestjs",
  "url": "claude-47-opus/javascript_nestjs.html",
  "source": "claude-47-opus/javascript_nestjs.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-47-opus",
  "modelName": "Claude Opus 4.7",
  "family": "claude",
  "type": "learning",
  "title": "GraphQL Academy — Préparation entretien Fullstack",
  "slug": "learning_graphql",
  "url": "claude-47-opus/learning_graphql.html",
  "source": "claude-47-opus/learning_graphql.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-47-opus",
  "modelName": "Claude Opus 4.7",
  "family": "claude",
  "type": "learning",
  "title": "ES6+ Playground — Apprendre le JavaScript moderne",
  "slug": "learning_javascript_es6plus",
  "url": "claude-47-opus/learning_javascript_es6plus.html",
  "source": "claude-47-opus/learning_javascript_es6plus.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-47-opus",
  "modelName": "Claude Opus 4.7",
  "family": "claude",
  "type": "learning",
  "title": "Polski — Apprendre le polonais",
  "slug": "learning_polish",
  "url": "claude-47-opus/learning_polish.html",
  "source": "claude-47-opus/learning_polish.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-47-opus",
  "modelName": "Claude Opus 4.7",
  "family": "claude",
  "type": "learning",
  "title": "React Mastery — Hooks, State & Components",
  "slug": "learning_react_hooks",
  "url": "claude-47-opus/learning_react_hooks.html",
  "source": "claude-47-opus/learning_react_hooks.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-47-opus",
  "modelName": "Claude Opus 4.7",
  "family": "claude",
  "type": "platformer",
  "title": "Neon Blaster — Platform Shooter",
  "slug": "platform-shooter",
  "url": "claude-47-opus/platform-shooter.html",
  "source": "claude-47-opus/platform-shooter.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-47-opus",
  "modelName": "Claude Opus 4.7",
  "family": "claude",
  "type": "platformer",
  "title": "Neon Shooter - Platform Game",
  "slug": "platform-shooter-old-max",
  "url": "claude-47-opus/platform-shooter-old-max.html",
  "source": "claude-47-opus/platform-shooter-old-max.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-48-opus",
  "modelName": "Claude Opus 4.8",
  "family": "claude",
  "type": "pachinko",
  "title": "PACHIROGUE — a pachinko roguelike",
  "slug": "pachinko",
  "url": "claude-48-opus/pachinko.html",
  "source": "claude-48-opus/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-48-opus",
  "modelName": "Claude Opus 4.8",
  "family": "claude",
  "type": "platformer",
  "title": "NEON BLASTER — Platform Shooter",
  "slug": "platform-shooter",
  "url": "claude-48-opus/platform-shooter.html",
  "source": "claude-48-opus/platform-shooter.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-48-opus-max",
  "modelName": "Claude Opus 4.8 · max",
  "family": "claude",
  "type": "city",
  "title": "RETRO CITY — Pixel City Builder",
  "slug": "city-builder-retro",
  "url": "claude-48-opus-max/city-builder-retro.html",
  "source": "claude-48-opus-max/city-builder-retro.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "claude-48-opus-max",
  "modelName": "Claude Opus 4.8 · max",
  "family": "claude",
  "type": "pachinko",
  "title": "Peg Dungeon — Roguelike Pachinko",
  "slug": "pachinko",
  "url": "claude-48-opus-max/pachinko.html",
  "source": "claude-48-opus-max/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "claude-fable-5-extra",
  "modelName": "Claude Fable 5 · extra",
  "family": "claude",
  "type": "learning",
  "title": "Big-O Dojo — apprendre la complexité algorithmique",
  "slug": "complexity",
  "url": "claude-fable-5-extra/complexity.html",
  "source": "claude-fable-5-extra/complexity.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "claude-fable-5-extra",
  "modelName": "Claude Fable 5 · extra",
  "family": "claude",
  "type": "learning",
  "title": "DistribuLab — Apprends les systèmes distribués",
  "slug": "distributed-system",
  "url": "claude-fable-5-extra/distributed-system.html",
  "source": "claude-fable-5-extra/distributed-system.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "claude-fable-5-extra",
  "modelName": "Claude Fable 5 · extra",
  "family": "claude",
  "type": "learning",
  "title": "Data structures — le guide interactif",
  "slug": "listes",
  "url": "claude-fable-5-extra/listes.html",
  "source": "claude-fable-5-extra/listes.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "claude-fable-5-extra",
  "modelName": "Claude Fable 5 · extra",
  "family": "claude",
  "type": "learning",
  "title": "MessageFlow — Producers, Queues & Brokers",
  "slug": "messages",
  "url": "claude-fable-5-extra/messages.html",
  "source": "claude-fable-5-extra/messages.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "claude-fable-5-max",
  "modelName": "Claude Fable 5 · max",
  "family": "claude",
  "type": "city",
  "title": "PIXOPOLIS — City Builder Rétro",
  "slug": "city-builder-retro",
  "url": "claude-fable-5-max/city-builder-retro.html",
  "source": "claude-fable-5-max/city-builder-retro.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "claude-fable-5-max",
  "modelName": "Claude Fable 5 · max",
  "family": "claude",
  "type": "pachinko",
  "title": "Pachinko Abyssal — roguelike",
  "slug": "pachinko",
  "url": "claude-fable-5-max/pachinko.html",
  "source": "claude-fable-5-max/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "claude-opus-5-extra",
  "modelName": "Claude Opus 5 · extra",
  "family": "claude",
  "type": "learning",
  "title": "PHP 8.5 Academy — Préparation entretien",
  "slug": "php8.5",
  "url": "claude-opus-5-extra/php8.5.html",
  "source": "claude-opus-5-extra/php8.5.html",
  "playable": true,
  "react": false,
  "date": "2026-09-23"
 },
 {
  "model": "claude-opus-5-extra",
  "modelName": "Claude Opus 5 · extra",
  "family": "claude",
  "type": "learning",
  "title": "Scaleway Academy — Cloud, CLI & API",
  "slug": "scaleway",
  "url": "claude-opus-5-extra/scaleway.html",
  "source": "claude-opus-5-extra/scaleway.html",
  "playable": true,
  "react": false,
  "date": "2026-09-23"
 },
 {
  "model": "claude-opus-5-max",
  "modelName": "Claude Opus 5 · max",
  "family": "claude",
  "type": "simulation",
  "title": "Jardin Génétique — simulation de nature",
  "slug": "genetic-garden",
  "url": "claude-opus-5-max/genetic-garden/index.html",
  "source": "claude-opus-5-max/genetic-garden/index.html",
  "playable": true,
  "react": false,
  "date": "2026-08-22"
 },
 {
  "model": "claude-opus-5-max",
  "modelName": "Claude Opus 5 · max",
  "family": "claude",
  "type": "idle",
  "title": "ENTROPIE — Programme d'exploration profonde",
  "slug": "idle-game",
  "url": "claude-opus-5-max/idle-game.html",
  "source": "claude-opus-5-max/idle-game.html",
  "playable": true,
  "react": false,
  "date": "2026-07-27"
 },
 {
  "model": "claude-opus-5-max",
  "modelName": "Claude Opus 5 · max",
  "family": "claude",
  "type": "pachinko",
  "title": "Pachinko Infernal — Roguelike",
  "slug": "pachinko",
  "url": "claude-opus-5-max/pachinko.html",
  "source": "claude-opus-5-max/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-07-27"
 },
 {
  "model": "claude-opus-55-extra",
  "modelName": "Claude Opus 5.5 · extra",
  "family": "claude",
  "type": "other",
  "title": "Déménageurs du Dimanche",
  "slug": "friendslop",
  "url": "claude-opus-55-extra/friendslop.html",
  "source": "claude-opus-55-extra/friendslop.html",
  "playable": true,
  "react": false,
  "date": "2026-09-23"
 },
 {
  "model": "claude-opus-55-extra",
  "modelName": "Claude Opus 5.5 · extra",
  "family": "claude",
  "type": "simulation",
  "title": "Jardin Génétique",
  "slug": "genetic-garden",
  "url": "claude-opus-55-extra/genetic-garden/index.html",
  "source": "claude-opus-55-extra/genetic-garden/index.html",
  "playable": true,
  "react": false,
  "date": "2026-09-23"
 },
 {
  "model": "claude-opus-55-extra",
  "modelName": "Claude Opus 5.5 · extra",
  "family": "claude",
  "type": "other",
  "title": "Hurlelune — Chroniques d’une meute",
  "slug": "incremental",
  "url": "claude-opus-55-extra/incremental.html",
  "source": "claude-opus-55-extra/incremental.html",
  "playable": true,
  "react": false,
  "date": "2026-09-24"
 },
 {
  "model": "claude-opus-55-extra",
  "modelName": "Claude Opus 5.5 · extra",
  "family": "claude",
  "type": "other",
  "title": "Haute Mise — Casino incrémental",
  "slug": "incremental-casino",
  "url": "claude-opus-55-extra/incremental-casino.html",
  "source": "claude-opus-55-extra/incremental-casino.html",
  "playable": true,
  "react": false,
  "date": "2026-09-24"
 },
 {
  "model": "claude-opus-55-extra",
  "modelName": "Claude Opus 5.5 · extra",
  "family": "claude",
  "type": "pachinko",
  "title": "Pachinko Rogue — La Descente Néon",
  "slug": "pachinko",
  "url": "claude-opus-55-extra/pachinko.html",
  "source": "claude-opus-55-extra/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-09-23"
 },
 {
  "model": "claude-sonnet-5-extra",
  "modelName": "Claude Sonnet 5 · extra",
  "family": "claude",
  "type": "city",
  "title": "CITÉ RÉTRO — City Builder Pixel",
  "slug": "city-builder-retro",
  "url": "claude-sonnet-5-extra/city-builder-retro.html",
  "source": "claude-sonnet-5-extra/city-builder-retro.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "claude37sonnet",
  "modelName": "Claude 3.7 Sonnet",
  "family": "claude",
  "type": "idle",
  "title": "Idle Space1",
  "slug": "idle-space1",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/claude37sonnet/idle-space1",
  "source": "claude37sonnet/idle-space1/public/index.html",
  "playable": false,
  "react": true,
  "date": "2026-02-18"
 },
 {
  "model": "claude45opus",
  "modelName": "Claude Opus 4.5",
  "family": "claude",
  "type": "pachinko",
  "title": "🎰 Pachinko Dungeon",
  "slug": "index",
  "url": "claude45opus/index.html",
  "source": "claude45opus/index.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "codex-51-max",
  "modelName": "GPT-5.1 Codex Max",
  "family": "openai",
  "type": "pachinko",
  "title": "Pachinko Rogue",
  "slug": "pachinko1",
  "url": "codex-51-max/pachinko1.html",
  "source": "codex-51-max/pachinko1.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "codex53",
  "modelName": "GPT-5.3 Codex",
  "family": "openai",
  "type": "landing",
  "title": "LingoLeap — Learn Languages Faster",
  "slug": "landing-page #1",
  "url": "codex53/landing-page/index1.html",
  "source": "codex53/landing-page/index1.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "codex53",
  "modelName": "GPT-5.3 Codex",
  "family": "openai",
  "type": "landing",
  "title": "LingoSprint — Apprenez les langues plus vite",
  "slug": "landing-page #2",
  "url": "codex53/landing-page/index2.html",
  "source": "codex53/landing-page/index2.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "codex53",
  "modelName": "GPT-5.3 Codex",
  "family": "openai",
  "type": "landing",
  "title": "LingoLift — Learn Languages Faster",
  "slug": "landing-page #3",
  "url": "codex53/landing-page/index3.html",
  "source": "codex53/landing-page/index3.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "codex53",
  "modelName": "GPT-5.3 Codex",
  "family": "openai",
  "type": "landing",
  "title": "LingoLeap — Learn Languages Faster",
  "slug": "landing-page #4",
  "url": "codex53/landing-page/index4.html",
  "source": "codex53/landing-page/index4.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "codex53",
  "modelName": "GPT-5.3 Codex",
  "family": "openai",
  "type": "platformer",
  "title": "Neon Platform Shooter",
  "slug": "platform-shooter #1",
  "url": "codex53/platform-shooter/index1.html",
  "source": "codex53/platform-shooter/index1.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "codex53",
  "modelName": "GPT-5.3 Codex",
  "family": "openai",
  "type": "platformer",
  "title": "Neon Platform Shooter",
  "slug": "platform-shooter #2",
  "url": "codex53/platform-shooter/index2.html",
  "source": "codex53/platform-shooter/index2.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "codex53",
  "modelName": "GPT-5.3 Codex",
  "family": "openai",
  "type": "platformer",
  "title": "Neon Platform Shooter",
  "slug": "platform-shooter #3",
  "url": "codex53/platform-shooter/index3.html",
  "source": "codex53/platform-shooter/index3.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "codex53",
  "modelName": "GPT-5.3 Codex",
  "family": "openai",
  "type": "platformer",
  "title": "Neon Platform Shooter",
  "slug": "platform-shooter #4",
  "url": "codex53/platform-shooter/index4.html",
  "source": "codex53/platform-shooter/index4.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "codex53",
  "modelName": "GPT-5.3 Codex",
  "family": "openai",
  "type": "solar",
  "title": "Système Solaire Interactif",
  "slug": "solar-system",
  "url": "codex53/solar-system/index.html",
  "source": "codex53/solar-system/index.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "codex53-new",
  "modelName": "GPT-5.3 Codex · v2",
  "family": "openai",
  "type": "idle",
  "title": "Void Forge Idle",
  "slug": "idle-game",
  "url": "codex53-new/idle-game.html",
  "source": "codex53-new/idle-game.html",
  "playable": true,
  "react": false,
  "date": "2026-03-05"
 },
 {
  "model": "codex53-new",
  "modelName": "GPT-5.3 Codex · v2",
  "family": "openai",
  "type": "platformer",
  "title": "Platform Shooter 2D",
  "slug": "platform-shooter",
  "url": "codex53-new/platform-shooter.html",
  "source": "codex53-new/platform-shooter.html",
  "playable": true,
  "react": false,
  "date": "2026-03-05"
 },
 {
  "model": "codex53-new",
  "modelName": "GPT-5.3 Codex · v2",
  "family": "openai",
  "type": "solar",
  "title": "Explorateur du Système Solaire",
  "slug": "solar-system",
  "url": "codex53-new/solar-system.html",
  "source": "codex53-new/solar-system.html",
  "playable": true,
  "react": false,
  "date": "2026-03-05"
 },
 {
  "model": "deepseek-r1-0528",
  "modelName": "DeepSeek R1 0528",
  "family": "deepseek",
  "type": "idle",
  "title": "Idle Game",
  "slug": "idle-game",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/deepseek-r1-0528/idle-game",
  "source": "deepseek-r1-0528/idle-game/public/index.html",
  "playable": false,
  "react": true,
  "date": "2026-02-18"
 },
 {
  "model": "deepseek-v3-2",
  "modelName": "DeepSeek V3.2",
  "family": "deepseek",
  "type": "pachinko",
  "title": "Pachinko Roguelike",
  "slug": "pachinko",
  "url": "deepseek-v3-2/pachinko.html",
  "source": "deepseek-v3-2/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "deepseek-v32-speciale",
  "modelName": "DeepSeek V3.2 Speciale",
  "family": "deepseek",
  "type": "pachinko",
  "title": "Pachinko Roguelike",
  "slug": "pachinko",
  "url": "deepseek-v32-speciale/pachinko.html",
  "source": "deepseek-v32-speciale/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gemini-25-pro",
  "modelName": "Gemini 2.5 Pro",
  "family": "google",
  "type": "idle",
  "title": "Idle Game",
  "slug": "idle-game",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/gemini-25-pro/idle-game",
  "source": "gemini-25-pro/idle-game/public/index.html",
  "playable": false,
  "react": true,
  "date": "2025-03-26"
 },
 {
  "model": "gemini-25-pro",
  "modelName": "Gemini 2.5 Pro",
  "family": "google",
  "type": "luck",
  "title": "Loto",
  "slug": "loto",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/gemini-25-pro/loto",
  "source": "gemini-25-pro/loto/public/index.html",
  "playable": false,
  "react": true,
  "date": "2026-02-18"
 },
 {
  "model": "gemini-25-pro",
  "modelName": "Gemini 2.5 Pro",
  "family": "google",
  "type": "simulation",
  "title": "Perlin",
  "slug": "perlin",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/gemini-25-pro/perlin",
  "source": "gemini-25-pro/perlin/public/index.html",
  "playable": false,
  "react": true,
  "date": "2025-03-26"
 },
 {
  "model": "gemini-25-pro",
  "modelName": "Gemini 2.5 Pro",
  "family": "google",
  "type": "solar",
  "title": "Solar System",
  "slug": "solar-system",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/gemini-25-pro/solar-system",
  "source": "gemini-25-pro/solar-system/public/index.html",
  "playable": false,
  "react": true,
  "date": "2026-02-18"
 },
 {
  "model": "gemini-25-pro",
  "modelName": "Gemini 2.5 Pro",
  "family": "google",
  "type": "luck",
  "title": "Wheel",
  "slug": "wheel",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/gemini-25-pro/wheel",
  "source": "gemini-25-pro/wheel/public/index.html",
  "playable": false,
  "react": true,
  "date": "2026-02-18"
 },
 {
  "model": "gemini-31-pro",
  "modelName": "Gemini 3.1 Pro",
  "family": "google",
  "type": "solar",
  "title": "Système Solaire Dynamique & Éducatif",
  "slug": "solar-system",
  "url": "gemini-31-pro/solar-system.html",
  "source": "gemini-31-pro/solar-system.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "gemini-31-pro",
  "modelName": "Gemini 3.1 Pro",
  "family": "google",
  "type": "solar",
  "title": "Explorateur du Système Solaire - Édition Éducative",
  "slug": "solar-system-2",
  "url": "gemini-31-pro/solar-system-2.html",
  "source": "gemini-31-pro/solar-system-2.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "gemini-36-flash",
  "modelName": "Gemini 3.6 Flash",
  "family": "google",
  "type": "pachinko",
  "title": "PegRogues - Pachinko Roguelike",
  "slug": "pachinko",
  "url": "gemini-36-flash/pachinko.html",
  "source": "gemini-36-flash/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-07-27"
 },
 {
  "model": "gemini3-flash-preview",
  "modelName": "Gemini 3 Flash Preview",
  "family": "google",
  "type": "pachinko",
  "title": "Pachy-Dungeon Roguelike",
  "slug": "pachinko",
  "url": "gemini3-flash-preview/pachinko.html",
  "source": "gemini3-flash-preview/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gemini3-pro",
  "modelName": "Gemini 3 Pro",
  "family": "google",
  "type": "pachinko",
  "title": "Pachinko Rogue",
  "slug": "pachinko",
  "url": "gemini3-pro/pachinko.html",
  "source": "gemini3-pro/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gemma-4-e4b",
  "modelName": "Gemma 4 E4B",
  "family": "google",
  "type": "weather",
  "title": "Animated Weather Dashboard",
  "slug": "meteo",
  "url": "gemma-4-e4b/meteo.html",
  "source": "gemma-4-e4b/meteo.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "glm-4-7",
  "modelName": "GLM 4.7",
  "family": "zhipu",
  "type": "pachinko",
  "title": "Neon Pachinko Rogue",
  "slug": "pachinko",
  "url": "glm-4-7/pachinko.html",
  "source": "glm-4-7/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "glm-52",
  "modelName": "GLM 5.2",
  "family": "zhipu",
  "type": "pachinko",
  "title": "Pachinko Dungeon — Roguelike",
  "slug": "pachinko",
  "url": "glm-52/pachinko.html",
  "source": "glm-52/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "gpt-41",
  "modelName": "GPT-4.1",
  "family": "openai",
  "type": "idle",
  "title": "Idle Game",
  "slug": "idle-game",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/gpt-41/idle-game",
  "source": "gpt-41/idle-game/public/index.html",
  "playable": false,
  "react": true,
  "date": "2026-02-18"
 },
 {
  "model": "gpt-41",
  "modelName": "GPT-4.1",
  "family": "openai",
  "type": "solar",
  "title": "Solar System",
  "slug": "solar-system",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/gpt-41/solar-system",
  "source": "gpt-41/solar-system/public/index.html",
  "playable": false,
  "react": true,
  "date": "2026-02-18"
 },
 {
  "model": "gpt-41-mini",
  "modelName": "GPT-4.1 mini",
  "family": "openai",
  "type": "solar",
  "title": "Solar System",
  "slug": "solar-system",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/gpt-41-mini/solar-system",
  "source": "gpt-41-mini/solar-system/public/index.html",
  "playable": false,
  "react": true,
  "date": "2025-04-28"
 },
 {
  "model": "gpt-5",
  "modelName": "GPT-5",
  "family": "openai",
  "type": "svg",
  "title": "Magnificent Unicorn",
  "slug": "licorne-api-thinking",
  "url": "gpt-5/licorne-api-thinking.html",
  "source": "gpt-5/licorne-api-thinking.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gpt-5",
  "modelName": "GPT-5",
  "family": "openai",
  "type": "svg",
  "title": "Loup en SVG",
  "slug": "loup",
  "url": "gpt-5/loup.svg",
  "source": "gpt-5/loup.svg",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gpt-5",
  "modelName": "GPT-5",
  "family": "openai",
  "type": "svg",
  "title": "Loup Api",
  "slug": "loup-api",
  "url": "gpt-5/loup-api.svg",
  "source": "gpt-5/loup-api.svg",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gpt-5",
  "modelName": "GPT-5",
  "family": "openai",
  "type": "svg",
  "title": "Loup Thinking",
  "slug": "loup-thinking",
  "url": "gpt-5/loup-thinking.svg",
  "source": "gpt-5/loup-thinking.svg",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gpt-5",
  "modelName": "GPT-5",
  "family": "openai",
  "type": "weather",
  "title": "Animated Weather Cards",
  "slug": "meteo-api",
  "url": "gpt-5/meteo-api.html",
  "source": "gpt-5/meteo-api.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gpt-5",
  "modelName": "GPT-5",
  "family": "openai",
  "type": "solar",
  "title": "Système Solaire Interactif — Ludique et Éducatif",
  "slug": "solaire-api",
  "url": "gpt-5/solaire-api.html",
  "source": "gpt-5/solaire-api.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gpt-5-nano",
  "modelName": "GPT-5 nano",
  "family": "openai",
  "type": "svg",
  "title": "Loup stylisé",
  "slug": "loup",
  "url": "gpt-5-nano/loup.svg",
  "source": "gpt-5-nano/loup.svg",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gpt-51",
  "modelName": "GPT-5.1",
  "family": "openai",
  "type": "pachinko",
  "title": "Dungeon Pachinko - Roguelike",
  "slug": "pachinko",
  "url": "gpt-51/pachinko.html",
  "source": "gpt-51/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "gpt-54-xhigh",
  "modelName": "GPT-5.4 · xhigh",
  "family": "openai",
  "type": "idle",
  "title": "Axiom Drift",
  "slug": "idle-game",
  "url": "gpt-54-xhigh/idle-game.html",
  "source": "gpt-54-xhigh/idle-game.html",
  "playable": true,
  "react": false,
  "date": "2026-03-25"
 },
 {
  "model": "gpt-54-xhigh",
  "modelName": "GPT-5.4 · xhigh",
  "family": "openai",
  "type": "solar",
  "title": "Planetarium orbital interactif",
  "slug": "solar-system",
  "url": "gpt-54-xhigh/solar-system.html",
  "source": "gpt-54-xhigh/solar-system.html",
  "playable": true,
  "react": false,
  "date": "2026-03-25"
 },
 {
  "model": "gpt-54-xhigh",
  "modelName": "GPT-5.4 · xhigh",
  "family": "openai",
  "type": "weather",
  "title": "Animated Weather Cards",
  "slug": "weather",
  "url": "gpt-54-xhigh/weather.html",
  "source": "gpt-54-xhigh/weather.html",
  "playable": true,
  "react": false,
  "date": "2026-03-25"
 },
 {
  "model": "gpt-55",
  "modelName": "GPT-5.5",
  "family": "openai",
  "type": "tool",
  "title": "2D Animator",
  "slug": "2d-animator",
  "url": "gpt-55/2d-animator.html",
  "source": "gpt-55/2d-animator.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "gpt-55",
  "modelName": "GPT-5.5",
  "family": "openai",
  "type": "simulation",
  "title": "Genetic Garden",
  "slug": "genetic-garden",
  "url": "gpt-55/genetic-garden/index.html",
  "source": "gpt-55/genetic-garden/index.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "gpt-55",
  "modelName": "GPT-5.5",
  "family": "openai",
  "type": "pachinko",
  "title": "Pachinko des Failles",
  "slug": "pachinko",
  "url": "gpt-55/pachinko.html",
  "source": "gpt-55/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "gpt-55",
  "modelName": "GPT-5.5",
  "family": "openai",
  "type": "platformer",
  "title": "Neon Rift Runner",
  "slug": "platform-shooter",
  "url": "gpt-55/platform-shooter.html",
  "source": "gpt-55/platform-shooter.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "gpt-55-with-goal",
  "modelName": "GPT-5.5 · avec objectif",
  "family": "openai",
  "type": "pachinko",
  "title": "Chute d'Astres - Roguelike Pachinko",
  "slug": "pachinko",
  "url": "gpt-55-with-goal/pachinko.html",
  "source": "gpt-55-with-goal/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-06-08"
 },
 {
  "model": "gpt-56-sol-extra",
  "modelName": "GPT-5.6 Sol · extra",
  "family": "openai",
  "type": "pachinko",
  "title": "Plinkomancie — Roguelike Pachinko",
  "slug": "pachinko",
  "url": "gpt-56-sol-extra/pachinko.html",
  "source": "gpt-56-sol-extra/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "gpt-56-sol-ultra",
  "modelName": "GPT-5.6 Sol · ultra",
  "family": "openai",
  "type": "pachinko",
  "title": "Faille // 7 — Pachinko Roguelike",
  "slug": "pachinko",
  "url": "gpt-56-sol-ultra/pachinko.html",
  "source": "gpt-56-sol-ultra/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "gpt-6-ultra",
  "modelName": "GPT-6 · ultra",
  "family": "openai",
  "type": "pachinko",
  "title": "NADIR — Les billes du destin",
  "slug": "pachinko",
  "url": "gpt-6-ultra/pachinko.html",
  "source": "gpt-6-ultra/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-09-23"
 },
 {
  "model": "gpt-oss-120b",
  "modelName": "GPT-OSS 120B",
  "family": "openai",
  "type": "svg",
  "title": "Loup en SVG",
  "slug": "svg-wolf",
  "url": "gpt-oss-120b/svg-wolf/index.html",
  "source": "gpt-oss-120b/svg-wolf/index.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "grok-35",
  "modelName": "Grok 3.5",
  "family": "xai",
  "type": "simulation",
  "title": "3d Fluid Simulation",
  "slug": "3d-fluid-simulation",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/grok-35/3d-fluid-simulation",
  "source": "grok-35/3d-fluid-simulation/public/index.html",
  "playable": false,
  "react": true,
  "date": "2026-02-18"
 },
 {
  "model": "grok-35",
  "modelName": "Grok 3.5",
  "family": "xai",
  "type": "idle",
  "title": "Idle Game",
  "slug": "idle-game",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/grok-35/idle-game",
  "source": "grok-35/idle-game/public/index.html",
  "playable": false,
  "react": true,
  "date": "2026-02-18"
 },
 {
  "model": "grok-35",
  "modelName": "Grok 3.5",
  "family": "xai",
  "type": "solar",
  "title": "Solar System",
  "slug": "solar-system",
  "url": "https://github.com/FeralDrak/ai-generated-apps/tree/main/grok-35/solar-system",
  "source": "grok-35/solar-system/public/index.html",
  "playable": false,
  "react": true,
  "date": "2026-02-18"
 },
 {
  "model": "grok-420",
  "modelName": "Grok 4.20",
  "family": "xai",
  "type": "landing",
  "title": "LinguaLeap • Apprends des langues en sautant les obstacles",
  "slug": "landing-page",
  "url": "grok-420/landing-page.html",
  "source": "grok-420/landing-page.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "grok-420",
  "modelName": "Grok 4.20",
  "family": "xai",
  "type": "platformer",
  "title": "🚀 NEO JUMP SHOOTER - Plateforme 2D Fun !",
  "slug": "platform-shooter",
  "url": "grok-420/platform-shooter.html",
  "source": "grok-420/platform-shooter.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "grok-420",
  "modelName": "Grok 4.20",
  "family": "xai",
  "type": "solar",
  "title": "🌌 Système Solaire Interactif",
  "slug": "solar-system",
  "url": "grok-420/solar-system.html",
  "source": "grok-420/solar-system.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "grok-45",
  "modelName": "Grok 4.5",
  "family": "xai",
  "type": "pachinko",
  "title": "Pachinko des Abysses",
  "slug": "pachinko",
  "url": "grok-45/pachinko.html",
  "source": "grok-45/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "grok-46",
  "modelName": "Grok 4.6",
  "family": "xai",
  "type": "pachinko",
  "title": "KACHINKO — Roguelike Pachinko",
  "slug": "pachinko",
  "url": "grok-46/pachinko.html",
  "source": "grok-46/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-08-22"
 },
 {
  "model": "grok-code-fast1",
  "modelName": "Grok Code Fast 1",
  "family": "xai",
  "type": "pachinko",
  "title": "Pachinko Roguelike",
  "slug": "pachinko",
  "url": "grok-code-fast1/pachinko.html",
  "source": "grok-code-fast1/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-02-18"
 },
 {
  "model": "kimi-k3",
  "modelName": "Kimi K3",
  "family": "moonshot",
  "type": "pachinko",
  "title": "Pachinko Roguelike",
  "slug": "pachinko",
  "url": "kimi-k3/pachinko.html",
  "source": "kimi-k3/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-07-22"
 },
 {
  "model": "qwen-35-9b",
  "modelName": "Qwen 3.5 9B",
  "family": "qwen",
  "type": "landing",
  "title": "LinguaFlow - Apprenez à parler, pas juste traduire.",
  "slug": "landing-page",
  "url": "qwen-35-9b/landing-page.html",
  "source": "qwen-35-9b/landing-page.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "qwen-35-9b",
  "modelName": "Qwen 3.5 9B",
  "family": "qwen",
  "type": "landing",
  "title": "LinguoFlow - Apprenez une langue en s'amusant",
  "slug": "landing-page-opus",
  "url": "qwen-35-9b/landing-page-opus.html",
  "source": "qwen-35-9b/landing-page-opus.html",
  "playable": true,
  "react": false,
  "date": "2026-03-05"
 },
 {
  "model": "qwen-35-9b",
  "modelName": "Qwen 3.5 9B",
  "family": "qwen",
  "type": "weather",
  "title": "Animated Weather Cards",
  "slug": "landing-page2",
  "url": "qwen-35-9b/landing-page2.html",
  "source": "qwen-35-9b/landing-page2.html",
  "playable": true,
  "react": false,
  "date": "2026-03-25"
 },
 {
  "model": "qwen-35-9b",
  "modelName": "Qwen 3.5 9B",
  "family": "qwen",
  "type": "svg",
  "title": "Loup",
  "slug": "loup",
  "url": "qwen-35-9b/loup.svg",
  "source": "qwen-35-9b/loup.svg",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "qwen-35-9b",
  "modelName": "Qwen 3.5 9B",
  "family": "qwen",
  "type": "solar",
  "title": "Système Solaire Interactif",
  "slug": "solar-system",
  "url": "qwen-35-9b/solar-system.html",
  "source": "qwen-35-9b/solar-system.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "qwen-35-9b",
  "modelName": "Qwen 3.5 9B",
  "family": "qwen",
  "type": "solar",
  "title": "CosmoExplorer - Système Solaire Interactif",
  "slug": "solar-system-opus",
  "url": "qwen-35-9b/solar-system-opus.html",
  "source": "qwen-35-9b/solar-system-opus.html",
  "playable": true,
  "react": false,
  "date": "2026-03-05"
 },
 {
  "model": "qwen-35-9b",
  "modelName": "Qwen 3.5 9B",
  "family": "qwen",
  "type": "solar",
  "title": "L'Explorateur Solaire Interactif",
  "slug": "solar-system-opus2",
  "url": "qwen-35-9b/solar-system-opus2.html",
  "source": "qwen-35-9b/solar-system-opus2.html",
  "playable": true,
  "react": false,
  "date": "2026-03-25"
 },
 {
  "model": "qwen-35-9b",
  "modelName": "Qwen 3.5 9B",
  "family": "qwen",
  "type": "weather",
  "title": "Animated Weather Cards",
  "slug": "weather",
  "url": "qwen-35-9b/weather.html",
  "source": "qwen-35-9b/weather.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "qwen-35-9b",
  "modelName": "Qwen 3.5 9B",
  "family": "qwen",
  "type": "weather",
  "title": "Animated Weather Cards",
  "slug": "weather-opus",
  "url": "qwen-35-9b/weather-opus.html",
  "source": "qwen-35-9b/weather-opus.html",
  "playable": true,
  "react": false,
  "date": "2026-03-05"
 },
 {
  "model": "qwen-35-flash",
  "modelName": "Qwen 3.5 Flash",
  "family": "qwen",
  "type": "landing",
  "title": "LingoFlow - Apprenez l'anglais (et plus encore) en rythme",
  "slug": "landing-page",
  "url": "qwen-35-flash/landing-page.html",
  "source": "qwen-35-flash/landing-page.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "qwen-35-flash",
  "modelName": "Qwen 3.5 Flash",
  "family": "qwen",
  "type": "svg",
  "title": "Loup",
  "slug": "loup",
  "url": "qwen-35-flash/loup.svg",
  "source": "qwen-35-flash/loup.svg",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "qwen-35-flash",
  "modelName": "Qwen 3.5 Flash",
  "family": "qwen",
  "type": "solar",
  "title": "Système Solaire Interactif",
  "slug": "solar-system",
  "url": "qwen-35-flash/solar-system.html",
  "source": "qwen-35-flash/solar-system.html",
  "playable": true,
  "react": false,
  "date": "2026-03-04"
 },
 {
  "model": "qwen-38-2400b-a95b",
  "modelName": "Qwen 3.8 2400B-A95B",
  "family": "qwen",
  "type": "pachinko",
  "title": "PACHIROGUE — pachinko roguelike néon",
  "slug": "pachinko",
  "url": "qwen-38-2400b-a95b/pachinko.html",
  "source": "qwen-38-2400b-a95b/pachinko.html",
  "playable": true,
  "react": false,
  "date": "2026-08-22"
 }
];
